# Generated by Django 5.0.6 on 2024-07-14 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unieventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-created',)},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='updated_at',
            new_name='updated',
        ),
    ]
