# Generated by Django 5.0.6 on 2024-07-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unieventos', '0003_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='registered',
            new_name='created',
        ),
        migrations.AddField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('Registered', 'Registered'), ('Canceled', 'Canceled')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
