# Generated by Django 5.0.6 on 2024-07-14 19:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unieventos', '0004_rename_registered_registration_created_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registrations',
            field=models.ManyToManyField(blank=True, related_name='registrations', to=settings.AUTH_USER_MODEL),
        ),
    ]
