# Generated by Django 5.0.6 on 2024-07-14 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unieventos', '0005_event_registrations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='registrations',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
